src/Entity/Activite.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActiviteRepository")
 * @Vich\Uploadable()
 * @UniqueEntity("Title")
 */
class Activite
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=600)
     */
    private $Filename;

    /**
 * @var File|null
 * @Assert\Image(
 *      mimeTypes="image/jpeg")
 * @Vich\UploadableField(mapping="activite_image",fileNameProperty="Filename")
 */   
private $imageFile;

/**
 * @ORM\Column(type="datetime")
 */
private $updated_at;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): string
    {
       return (new Slugify())->slugify($this->getTitle());
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->Filename;
    }

    public function setFilename( $Filename): Activite
    {
        $this->Filename = $Filename;

        return $this;
    }

    public function getImageFile(): ?File
{
    return $this->imageFile;
}

    public function setImageFile(File $imageFile): self
{
    $this->imageFile = $imageFile;
    if ($this->imageFile instanceof UploadedFile) {
        $this->updated_at = new \DateTime('now');
    }
    return $this;

}
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of Description
     */ 
    public function getDescription(): ?string
    {
        return $this->Description;
    }

    /**
     * Set the value of Description
     *
     * @return  self
     */ 
    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

templates/pages/activites.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos activités {% endblock %}

{% block body %}

<h1 class="text-center">Nos différentes activités sportives</h1>

<div class="container">
    <div class="row">
 {% for activite in activites %}
        <div class="col-md-4">
    <div class="card mb-4">
        {% if activite.filename %}
    <img src=" {{vich_uploader_asset(activite, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top">
        {% endif %}
    <div class="card-body">
       <div class="card-header">
      <a href="{{ path('activite.show', {id: activite.id, slug: activite.slug}) }}"> {{ activite.title }} </a>

        
           

</div>
    </div>
</div>

</div>
{% endfor %}
</div>








{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %} Contactez nous {% endblock %}

{% block body %}

<h1 class="text-center">Contact</h1>
<div class="container-fluid">
    
    <div class="row">
            
        <div class="col-sm-4">
            <h3>Notre Localisation</h3>
            <div class="card">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d663.7013377266148!2d6.952371629256929!3d48.28736049870221!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4793eea22234c567%3A0x5d3dde8a06b0d6f2!2s8%20Rue%20des%20Fr%C3%A8res%20Simon%2C%2088100%20Saint-Di%C3%A9-des-Vosges!5e0!3m2!1sfr!2sfr!4v1568123109011!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>

        <div class="col-sm-4">
            <h3>Nos coordonnées</h3>
            <p>Fit and Fight <br>
                6/8 rue des frères simon <br>
                88100 Saint Dié des vosges
            </p>
            <p>TEL: 07.88.51.71.30</p>
            <p>Email: contact@fitandfight.fr</p>
        </div>

        <div class="col-sm-4">
                {% for message in app.flashes('success') %} 
                <div class="alert alert-success">
                    {{ message }}
                </div>
                {% endfor %}
            <h3>Formulaire de contact</h3>

            {{ form_start(form) }}
           
            {{ form_rest(form) }}
            


        <button class="btn btn-primary" type="submit">Envoyer</button>

        {{ form_end(form)}}
        
        </div>
    </div>
</div>



{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}


{% block title  %} Bienvenue sur le site de FitandFight {% endblock %}

{% block body %}

<div class="container">
<div class="row">
<div class="card mt-3">
<div class="card-body">
<p class="text-center">L'association Fit and Fight a été créée cette année à l'initiative de Maëlan CAMA.<br>
Nous avons débutés notre association à Mandray dans une salle des fêtes.<br>
Grâce à nos licenciés nous avons pu avoir l'opportunité de nous installer au centre de Saint-Dié dans notre propre salle comptant 4 encadrants tous
diplômés dans plusieurs disciplines d'arts martiaux comme le Kick-Boxing, le Muay Thaï, le MMA et le Cross-Training.<br>
<br>

La salle d'entrainement est situé au 8 rue des frères Simon à Saint-Dié.Nous l'avons équipés d'une partie d'entrainement avec tapis,sac de frappe,
structure de préparation physique et d'une autre partie musculation avec des postes de musculation et un accès libre de 8h00 à 22h00 via un badge d'accès.</p>

<p class="text-center"> Nous vous souhaitons une agréable visite sur notre site et n'hésitez pas à prendre contact pour toutes questions et à très bientôt.</p>

</div>
</div>
</div>
</div>


{% endblock %}

templates/pages/mentionslegales.html.twig
{%  extends 'base.html.twig' %}

{% block title %}Mentions Légales {% endblock %}

{% block body %}

<div class="container">


<h2>Informations légales</h2>
<h3>1. Présentation du site.</h3>
<p>En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé aux utilisateurs du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi :</p>
<p><strong>Propriétaire</strong> : Fit and Fight: à chacun son combat – Association R.N.A : W883005577 – 6/8 rue des frères Simon 88100 Saint-Dié-des-Vosges<br />
<strong>Créateur</strong>  : <a href="www.fitandfight.fr">Fit and Fight</a><br />
<strong>Responsable publication</strong> : Fit and Fight – contact@fitandfight.fr<br />
Le responsable publication est une personne physique ou une personne morale.<br />
<strong>Webmaster</strong> : Rémy – contact@fitandfight.fr<br />
<strong>Hébergeur</strong> : LIGNE WEB SERVICES – 10, RUE PENTHIEVRE - 75008 PARIS<br />
Crédits : <br />
Le modèle de mentions légales est offert par Subdelirium.com <a target="_blank" href="https://www.subdelirium.com/generateur-de-mentions-legales/" alt="generateur de mentions légales">Générateur de mentions légales</a></p>

<h3>2. Conditions générales d’utilisation du site et des services proposés.</h3>
<p>L’utilisation du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> sont donc invités à les consulter de manière régulière.</p>
<p>Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par Fit and Fight: à chacun son combat, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
<p>Le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> est mis à jour régulièrement par Fit and Fight. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
<h3>3. Description des services fournis.</h3>
<p>Le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> a pour objet de fournir une information concernant l’ensemble des activités de la société.</p>
<p>Fit and Fight: à chacun son combat s’efforce de fournir sur le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> des informations aussi précises que possible. Toutefois, il ne pourra être tenue responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</p>
<p>Tous les informations indiquées sur le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
<h3>4. Limitations contractuelles sur les données techniques.</h3>
<p>Le site utilise la technologie JavaScript.</p>
<p>Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour</p>
<h3>5. Propriété intellectuelle et contrefaçons.</h3>
<p>Fit and Fight: à chacun son combat est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.</p>
<p>Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : Fit and Fight: à chacun son combat.</p>
<p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
<h3>6. Limitations de responsabilité.</h3>
<p>Fit and Fight: à chacun son combat ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site www.fitandfight.fr, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
<p>Fit and Fight: à chacun son combat ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a>.</p>
<p>Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. Fit and Fight: à chacun son combat se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, Fit and Fight: à chacun son combat se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…).</p>
<h3>7. Gestion des données personnelles.</h3>
<p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
<p>A l'occasion de l'utilisation du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a>, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur.</p>
<p> En tout état de cause Fit and Fight: à chacun son combat ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a>. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> l’obligation ou non de fournir ces informations.</p>
<p>Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
<p>Aucune information personnelle de l'utilisateur du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de Fit and Fight: à chacun son combat et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a>.</p>
<p>Le site n'est pas déclaré à la CNIL car il ne recueille pas d'informations personnelles. .</p>
<p>Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
<h3>8. Liens hypertextes et cookies.</h3>
<p>Le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Fit and Fight: à chacun son combat. Cependant, Fit and Fight: à chacun son combat n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
<p>La navigation sur le site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
<p>Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies :</p>
<p>Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok.</p>
<p>Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l'onglet Options. Cliquer sur l'onglet Vie privée.
  Paramétrez les Règles de conservation sur :  utiliser les paramètres personnalisés pour l'historique. Enfin décochez-la pour  désactiver les cookies.</p>
<p>Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur Paramètres de contenu. Dans la section "Cookies", vous pouvez bloquer les cookies.</p>
<p>Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur préférences.  Dans l'onglet "Confidentialité", vous pouvez bloquer les cookies.</p>

<h3>9. Droit applicable et attribution de juridiction.</h3>
<p>Tout litige en relation avec l’utilisation du site <a href="http://www.fitandfight.fr/">www.fitandfight.fr</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
<h3>10. Les principales lois concernées.</h3>
<p>Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés.</p>
<p> Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.</p>
<h3>11. Lexique.</h3>
<p>Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
<p>Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>

</div>

{% endblock %}